routes/web.php
<?php

use App\Http\Controllers\AgentController;
use App\Http\Controllers\AgentRateController;
use App\Http\Controllers\BankRateController;
use App\Http\Controllers\PrincipalController;
use App\Http\Controllers\BankAccountController;
use App\Http\Controllers\BankController;
use App\Http\Controllers\DesignController;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\InsuranceController;
use App\Http\Controllers\InsuranceTypeController;
use App\Http\Controllers\InsuranceRateController;
use App\Http\Controllers\ObligeeController;
use App\Http\Controllers\PDFDownloadController;
use App\Http\Controllers\RegionalController;
use App\Http\Controllers\Select2Controller;
use App\Http\Controllers\UploaderController;
use App\Http\Controllers\SuretyBondController;
use App\Http\Controllers\GuaranteeBankController;
use App\Http\Controllers\GuaranteeBankDraftController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\TemplateController;
use App\Http\Controllers\SuretyBondReportController;
use App\Http\Controllers\GuaranteeBankReportController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\InstalmentController;
use App\Http\Controllers\SuretyBondDraftController;
use App\Models\GuaranteeBankDraft;
use App\Models\SuretyBondDraft;
use Illuminate\Support\Facades\Route;
use App\Helpers\Jamsyar;
use App\Http\Controllers\GuaranteeBankReportPrintController;
use App\Http\Controllers\OtherReportController;
use App\Http\Controllers\OtherReportPrintController;
use App\Http\Controllers\SuretyBondReportPrintController;
use App\Http\Controllers\BankCostRateController;
use Illuminate\Support\Facades\Request;

/**
 * -------------------------------------------------------------------------
 * Design Only Route
 * -------------------------------------------------------------------------
 */

Route::get('/design/pdf/{page}', [DesignController::class, 'pdf'])->name('design.pdf');
Route::get('/design/{page}', [DesignController::class, 'page'])->name('design.page');

Route::get('/test', function (Request $request) {
    // dd(Jamsyar::cities('jsh','Semangat1','sura'));
    // dd(\App\Models\Branch::find(1)->table()->get());
    // dd(\App\Models\GuaranteeBank::table('remain',[])->get());
    // dd(\App\Models\Obligee::find(2)->sync());
    // dd(\App\Models\Principal::find(1)->sync());
    // dd(\App\Models\SuretyBond::find(5)->sync());
    // Jamsyar::token();
    // dd(Jamsyar::token());
});
Route::get('/subagent', function (Request $request) {
    $url = config('app.env') == 'local' ? 'http://devmicroservice.jamkrindosyariah.co.id/Api/get_subagen' : 'http://192.168.190.168:8002/Api/get_subagen';
    $response = \Illuminate\Support\Facades\Http::asJson()->acceptJson()->withToken(Jamsyar::login())
    ->post($url, [
        "kode_subagen" => "",
        "nama_subagen" => "",
        "limit" => 20,
        "offset" => 0
    ]);
    dd($response);
});


/**
 * -------------------------------------------------------------------------
 * Guest routes
 * -------------------------------------------------------------------------
 */
Route::get('request-surety-bond', [SuretyBondDraftController::class, 'indexClient'])->name('client');
Route::post('request-surety-bond', [SuretyBondDraftController::class, 'storeClient']);
Route::get('request-bank-garansi', [GuaranteeBankDraftController::class, 'indexClient'])->name('bgc');
Route::post('request-bank-garansi', [GuaranteeBankDraftController::class, 'storeClient']);
Route::get('principal-client/{principal}', [PrincipalController::class, 'show'])->name('client.principal');
Route::get('obligee-client/{obligee}', [ObligeeController::class, 'show'])->name('client.obligee');
Route::get('serviceworker.js', fn() => redirect()->route('main.dashboard')); // Entah kenapa beberapa kali login malah masuk ke sini

/**
 * -------------------------------------------------------------------------
 * Select2 Route
 * -------------------------------------------------------------------------
 */

Route::group(['prefix' => '/select2', 'as' => 'select2.'], function () {
    Route::get('regional',[Select2Controller::class,'regional'])->name('regional');
    Route::get('branch',[Select2Controller::class,'branch'])->name('branch');
    Route::get('branch-client',[Select2Controller::class,'branch_client'])->name('branchClient');
    Route::get('bank',[Select2Controller::class,'bank'])->name('bank');
    Route::get('province',[Select2Controller::class,'province'])->name('province');
    Route::get('city',[Select2Controller::class,'city'])->name('city');
    Route::get('agent',[Select2Controller::class,'agent'])->name('agent');
    Route::get('insurance',[Select2Controller::class,'insurance'])->name('insurance');
    Route::get('obligee',[Select2Controller::class,'obligee'])->name('obligee');
    Route::get('principal',[Select2Controller::class,'principal'])->name('principal');
    Route::get('insurance-type',[Select2Controller::class,'insuranceType'])->name('insuranceType');
    Route::get('suretyTemplate',[Select2Controller::class,'suretyTemplate'])->name('suretyTemplate');
    Route::get('bankTemplate/{id}',[Select2Controller::class,'bankTemplate'])->name('bankTemplate');
});

/*
|--------------------------------------------------------------------------
| Main Routes
|--------------------------------------------------------------------------
|
*/

Route::middleware(['auth'])->group(function () {
    Route::post('/uploader/tinymce', [UploaderController::class, 'tinyMCE'])->name('uploader.tinymce'); // tolong disesuaikan ya
    Route::get('/pdf/download/{id}', [PDFDownloadController::class, 'pdf']);
    Route::post('/pdf/download-template/', [PDFDownloadController::class, 'pdfTemplate'])->name('pdf.print');
    Route::post('/pdf/download-laporan-surety-bonds/', [PDFDownloadController::class, 'pdfSB'])->name('pdf.print.sb');

    // Master Data (bisa diakses di root dan beberapa di cabang)

    Route::group(['prefix' => '/master-data', 'as' => 'master.'], function () {
        Route::get('/', fn() => redirect(route('main.dashboard')));
        Route::apiResource('asuransi', InsuranceController::class)->names('insurances')->except('index');
        Route::apiResource('agen', AgentController::class)->names('agents')->except('index');
        Route::put('principal/{principal}/sync', [PrincipalController::class, 'sync'])->name('principals.sync');
        Route::post('principal/jamsyar-search', [PrincipalController::class, 'jamsyarSearch'])->name('principals.jamsyar-search');
        Route::post('principal/jamsyar-insert', [PrincipalController::class, 'jamsyarInsert'])->name('principals.jamsyar-insert');
        Route::apiResource('principal', PrincipalController::class)->names('principals')->except('index');
        Route::apiResource('rate-agen', AgentRateController::class)->names('agent-rates')->except('index');
        Route::apiResource('jenis-jaminan', InsuranceTypeController::class)->names('insurance-types')->except('index');
        Route::apiResource('rate-asuransi', InsuranceRateController::class)->names('insurance-rates')->except('index');
        Route::apiResource('rate-bank', BankRateController::class)->names('bank-rates')->except('index');
        Route::apiResource('bank', BankController::class)->names('banks')->except('index');
        Route::post('obligee/jamsyar-search', [ObligeeController::class, 'jamsyarSearch'])->name('obligees.jamsyar-search');
        Route::post('obligee/jamsyar-insert', [ObligeeController::class, 'jamsyarInsert'])->name('obligees.jamsyar-insert');
        Route::put('obligee/{obligee}/sync', [ObligeeController::class, 'sync'])->name('obligees.sync');
        Route::get('obligee/sync-with-jamsyar', [ObligeeController::class, 'jamsyar'])->name('obligees.jamsyar');
        Route::apiResource('obligee', ObligeeController::class)->names('obligees')->except('index');
        Route::apiResource('template', TemplateController::class)->names('templates')->except('index');
        Route::apiResource('bank-cost-rate', BankCostRateController::class)->names('bank-cost-rates')->except('index');
    });

    // Pembayaran (beberapa aksi bisa diakses di semua role)

    Route::group(['prefix' => '/pembayaran', 'as' => 'payments.'], function () {
        Route::get('/', [PaymentController::class, 'tables'])->name('tables');
        Route::post('hitung', [PaymentController::class, 'calculate'])->name('calculate');
        Route::apiResource('/payment', PaymentController::class, ['only' => ['store', 'show', 'destroy']])->names('payment');
    });

    // Admin Pusat

    Route::group(['middleware' => 'main', 'as' => 'main.'], function () {
        Route::get('/', DashboardController::class)->name('dashboard');
        Route::get('/profil', [ProfileController::class, 'index'])->name('profile');
        Route::apiResource('regional', RegionalController::class)->names('regionals');

        Route::group(['prefix' => '/master-data', 'as' => 'master.'], function () {
            Route::get('/', fn() => redirect(route('main.dashboard')));
            Route::get('asuransi', [InsuranceController::class, 'index'])->name('insurances.index');
            Route::get('agen', [AgentController::class, 'index'])->name('agents.index');
            Route::get('principal', [PrincipalController::class, 'index'])->name('principals.index');
            Route::get('rate-agen', [AgentRateController::class, 'index'])->name('agent-rates.index');
            Route::get('jenis-jaminan', [InsuranceTypeController::class, 'index'])->name('insurance-types.index');
            Route::get('rate-asuransi', [InsuranceRateController::class, 'index'])->name('insurance-rates.index');
            Route::get('rate-bank', [BankRateController::class, 'index'])->name('bank-rates.index');
            Route::get('bank', [BankController::class, 'index'])->name('banks.index');

resources/views/branches.blade.php
@extends('layouts.main', ['title' => 'Cabang'])

@push('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
@endpush

@section('contents')
    <x-card header="Daftar Cabang">
        @slot('headerAction')
            <x-button data-bs-toggle="modal" data-bs-target="#modal-create" size="sm" icon="bx bx-plus">Tambah Cabang</x-button>
        @endslot

        <x-table id="table">
            @slot('thead')
                <tr>
                    <th width="10px">No.</th>
                    <th>Nama</th>
                    <th>Username Jamsyar</th>
                    <th>Nama Pengguna</th>
                    <th>Username Pengguna</th>
                    <th width="120px">Tindakan</th>
                </tr>
            @endslot
        </x-table>
    </x-card>
@endsection

@section('modals')
    <x-modal id="modal-create" title="Tambah Cabang">
        <x-form id="form-create" method="post">
            <input type="hidden" name="regionalId" value="{{ $global->regional->id }}">
            <x-form-input id="create-name" name="name" label="Nama" class="mb-3" required/>
            <x-form-input id="create-jamsyar-username" name="jamsyar_username" label="Username Jamsyar" class="mb-3" required />
            <x-form-input id="create-jamsyar-password" name="jamsyar_password" label="Password Jamsyar" class="mb-3" type="password" required />
            <hr>
            <x-form-input id="create-login-name" name="login_name" label="Nama Pengguna" class="mb-3" required />
            <x-form-input id="create-login-username" name="login_username" label="Username Pengguna" class="mb-3" required />
            <x-form-input id="create-login-password" name="login_password" label="Password Pengguna" class="mb-3" type="password" required />
            <x-form-input id="create-login-password-confirmation" name="login_password_confirmation" label="Konfirmasi Password Pengguna" class="mb-3" type="password" required />
        </x-form>

        @slot('footer')
            <x-button id="create-save" face="success" icon="bx bxs-save">Simpan</x-button>
        @endslot
    </x-modal>

    <x-modal id="modal-show" title="Detail Cabang">
        <div class="border-bottom pb-2 mb-2">
            <b>Nama</b>: <br>
            <span id="show-name">-</span>
        </div>
        <div class="border-bottom mb-2 pb-2">
            <b>Username Jamsyar</b>: <br>
            <span id="show-jamsyar-username">-</span>
        </div>
        <div>
            <b>Password Jamsyar</b>: <br>
            <span id="show-jamsyar-password">-</span>
        </div>
        <hr>
        <div class="border-bottom mb-2 pb-2">
            <b>Nama Pengguna</b>: <br>
            <span id="show-login-name">-</span>
        </div>
        <div>
            <b>Username Pengguna</b>: <br>
            <span id="show-login-username">-</span>
        </div>

        @slot('footer')
            <x-button class="btn-edit" data-bs-target="#modal-edit" data-bs-toggle="modal" data-bs-dismiss="modal" face="warning" icon="bx bxs-edit">Ubah</x-button>
        @endslot
    </x-modal>

    <x-modal id="modal-edit" title="Ubah Cabang">
        <x-form id="form-edit" method="put">
            <input type="hidden" name="regionalId" value="{{ $global->regional->id }}">
            <x-form-input id="edit-name" name="name" label="Nama" class="mb-3" required />
            <x-form-input id="edit-jamsyar-username" name="jamsyar_username" label="Username Jamsyar" class="mb-3" required />
            <x-form-input id="edit-jamsyar-password" name="jamsyar_password" label="Password Jamsyar" class="mb-3" type="password" required />
            <hr>
            <x-form-input id="edit-login-name" name="login_name" label="Nama Pengguna" class="mb-3" required />
            <x-form-input id="edit-login-username" name="login_username" label="Username Pengguna" class="mb-3" required />
            <hr>
            <x-form-input id="edit-password" name="login_password" label="Ganti Password" class="mb-3" type="password" />
            <x-form-input id="edit-password-confirmation" name="login_password_confirmation" label="Konfirmasi Password Baru" type="password" />
        </x-form>

        @slot('footer')
            <div class="d-flex justify-content-between w-100">
                <x-button data-bs-target="#modal-show" data-bs-toggle="modal" data-bs-dismiss="modal" face="dark" icon="bx bx-arrow-back">Kembali</x-button>
                <x-button id="edit-save" face="success" icon="bx bxs-save">Simpan</x-button>
            </div>
        @endslot
    </x-modal>
@endsection

@push('js')
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        let table = null
        let branch = null
        $(document).ready(function () {
            table = dataTableInit('table','Cabang',{url : '{{ route('regional.branches.index', ['regional' => $global->regional->slug]) }}'},[
                {data: 'name', name: 'name'},
                {data: 'jamsyar_username', name: 'jamsyar_username'},
                {data: 'login_name', name: 'u.name'},
                {data: 'login_username', name: 'u.username'},
            ])
            select2Init("#create-regional-id",'{{ route('select2.regional') }}',0,$('#modal-create'))
            select2Init("#edit-regional-id",'{{ route('select2.regional') }}',0,$('#modal-edit'))
        })
        $(document).on('click', '#create-save', function () {
            loading()
            let formData = new FormData(document.getElementById('form-create'))
            formData.append('is_regional',0)
            ajaxPost("{{ route('regional.branches.store', ['regional' => $global->regional->slug]) }}",formData,'#modal-create',function(){
                table.ajax.reload()
                clearForm('#form-create')
            })
        })
        $(document).on('click', '#edit-save', function () {
            loading()
            let formData = new FormData(document.getElementById('form-edit'))
            formData.append('is_regional',0)
            ajaxPost("{{ route('regional.branches.update', ['regional' => $global->regional->slug, 'cabang' => '-id-']) }}".replace('-id-',branch.id),formData,'#modal-edit',function(){
                table.ajax.reload()
            })
        })
        $(document).on('click', '.btn-show', function () {
            ajaxGet("{{ route('regional.branches.show', ['regional' => $global->regional->slug, 'cabang' => '-id-']) }}".replace('-id-',$(this).data('id')),'',function(response){
                if(response.success){
                    branch = response.data
                    $('#show-regional').html(branch.regional.name)
                    $('#show-name').html(branch.name)
                    $('#show-jamsyar-username').html(branch.jamsyar_username)
                    $('#show-jamsyar-password').html(branch.jamsyar_password_masked)
                    $('#show-login-name').html(branch.user.name)
                    $('#show-login-username').html(branch.user.username)
                }
            })
        })
        $(document).on('click', '.btn-edit', function () {
            $('#edit-name').val(branch.name)
            $('#edit-regional-id').append(new Option(branch.regional.name,branch.regional.id,true,true)).trigger('change');
            $('#edit-jamsyar-username').val(branch.jamsyar_username)
            $('#edit-jamsyar-password').val(branch.jamsyar_password)
            $('#edit-login-name').val(branch.user.name)
            $('#edit-login-username').val(branch.user.username)
        })
        $(document).on('click', '.btn-delete', function () {
            // Delete
            NegativeConfirm.fire({
                title: "Yakin ingin menghapus cabang " + $(this).data('name') + "?",
            }).then((result) => {
                if (result.isConfirmed) {
                    loading()
                    let formData = new FormData()
                    formData.append('_method','delete')
                    ajaxPost("{{ route('regional.branches.destroy', ['regional' => $global->regional->slug, 'cabang' => '-id-']) }}".replace('-id-',$(this).data('id')),formData,'',function(){
                        table.ajax.reload()
                    })
                }
            })
        })
    </script>
@endpush

resources/views/guarantee-banks-client.blade.php
@extends('layouts.client', ['title' => 'Request Bank Garansi'])

@push('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
@endpush

@section('contents')
    <x-card header="Request Bank Garansi">
        <div class="border rounded p-2" style="background-color: #EEE">
            <x-form id="form-create" method="post">
                <div class="row mb-4">
                    <div class="col-12 text-center">
                        <div class="h5 fw-bold border-bottom mb-3 pb-2">Informasi Bank Garansi</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="w-100 mb-4">
                            <x-card header="Data" smallHeader>
                                <x-form-select label="Cabang" id="create-branch-id" name="branchId" class="mb-3" required/>
                                <x-form-input label="No. Bond" id="create-bond-number" name="bondNumber" class="mb-3" />
                                <x-form-input label="No. Polis" id="create-polish-number" name="polishNumber" class="mb-3" />
                                <x-form-select label="Nama Agen" id="create-agent-id" :options="[]" name="agentId" class="mb-3" required/>
                                <x-form-select label="Nama Bank" id="create-bank-id" :options="[]" name="bankId" class="mb-3" required/>
                                <x-form-select label="Nama Asuransi" id="create-insurance-id" :options="[]" name="insuranceId" class="mb-3" required/>
                                <x-form-select label="Jenis Jaminan" id="create-insurance-type-id" :options="[]" name="insuranceTypeId" required/>
                            </x-card>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="w-100 mb-4">
                            <x-card header="Principal" smallHeader>
                                <x-form-select label="Nama" id="create-principal-id" :options="[]" name="principalId" class="mb-3" required/>
                                <div class="mb-3">
                                    <x-form-label>Alamat</x-form-label>
                                    <div id="create-principal-address">-</div>
                                </div>
                                <div class="mb-3">
                                    <x-form-label>Nama PIC</x-form-label>
                                    <div id="create-pic-name">-</div>
                                </div>
                                <div>
                                    <x-form-label>Jabatan PIC</x-form-label>
                                    <div id="create-pic-position">-</div>
                                </div>
                            </x-card>
                        </div>
                        <div class="w-100 mb-4">
                            <x-card header="Obligee" smallHeader>
                                <x-form-select label="Nama" id="create-obligee-id" :options="[]" name="obligeeId" class="mb-3" required/>
                                <div>
                                    <x-form-label>Alamat</x-form-label>
                                    <div id="create-obligee-address">-</div>
                                </div>
                            </x-card>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="w-100 mb-4">
                            <x-card header="Jaminan" smallHeader>
                                <x-form-input label="Nilai Kontrak" id="create-contract-value" name="contractValue" prefix="Rp. " class="mb-3" classInput="to-unit" data-decimals="2" required />
                                <x-form-input label="Nilai Jaminan" id="create-insurance-value" name="insuranceValue" prefix="Rp. " class="mb-3" classInput="to-unit" data-decimals="2" required />
                                <div class="row">
                                    <div class="col-sm-6">
                                        <x-form-input label="Jangka Awal" id="create-start-date" name="startDate" type="date" class="mb-3" />
                                    </div>
                                    <div class="col-sm-6">
                                        <x-form-input label="Jangka Akhir" id="create-end-date" name="endDate" type="date" class="mb-3" />
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <x-form-label>Batas Toleransi Jatuh Tempo</x-form-label>
                                    <div class="d-flex flex-xl-row flex-column gap-2">
                                        <x-form-check id="create-due-day-tolerance-0" input-class='create-due-day-tolerance' name='dueDayTolerance' value="0" type="radio" inline checked>0 Hari</x-form-check>
                                        <x-form-check id="create-due-day-tolerance-1" input-class='create-due-day-tolerance' name='dueDayTolerance' value="1" type="radio" inline>1 Hari</x-form-check>
                                        <x-form-check id="create-due-day-tolerance-2" input-class='create-due-day-tolerance' name='dueDayTolerance' value="2" type="radio" inline>2 Hari</x-form-check>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <x-form-label required>Jumlah Hari</x-form-label>
                                    <input type="hidden" id="create-day-count-input" name="dayCount" value="0">
                                    <div><span id="create-day-count">0</span> Hari</div>
                                </div>
                                <x-form-input label="Nama Proyek" id="create-project-name" name="projectName" class="mb-3" required />
                                <x-form-input label="Dokumen Pendukung" id="create-document-title" name="documentTitle" class="mb-3" required />
                                <x-form-input label="No. Dokumen Pendukung" id="create-document-number" name="documentNumber" class="mb-3" required />
                                <x-form-input label="Tanggal Dokumen Pendukung" id="create-document-expired-at" name="documentExpiredAt" type="date" required />
                            </x-card>
                        </div>
                    </div>
                </div>
            </x-form>
        </div>
        @slot('footer')
            <div class="text-end">
                <x-button id="create-save" face="success" icon="bx bxs-save">Simpan</x-button>
            </div>
        @endslot
    </x-card>
@endsection

@push('js')
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        let table = null
        let guaranteeBank = null
        $(document).ready(function () {
            select2Init("#create-branch-id",'{{ route('select2.branchClient') }}',0)
            select2Init("#create-agent-id",'{{ route('select2.agent') }}',null,0,'-- Pilih --',false,function(params) {
                return {
                    search: params.term ?? '',
                    branchId: $('#create-branch-id').val(),
                }
            })
            select2Init("#create-obligee-id",'{{ route('select2.obligee') }}',0)
            select2Init("#create-principal-id",'{{ route('select2.principal') }}',0)
            select2Init("#create-insurance-id",'{{ route('select2.insurance') }}',0)
            select2Init("#create-insurance-type-id",'{{ route('select2.insuranceType') }}',0)
            select2Init("#create-bank-id",'{{ route('select2.bank') }}',0)
        })

        $(document).on('change', '#create-branch-id', function () {
            $("#create-agent-id").val(null).trigger('change')
        })
        $(document).on('input', '#create-service-charge, #create-admin-charge', function () {
            const creadit = $(this).attr('id').split('-')[0] //create or edit
            const serviceCharge = parseInt($('#'+creadit+'-service-charge').val() ? $('#'+creadit+'-service-charge').val().replaceAll('.','') : 0)
            const adminCharge = parseInt($('#'+creadit+'-admin-charge').val() ? $('#'+creadit+'-admin-charge').val().replaceAll('.','') : 0)
            const totalCharge =  serviceCharge + adminCharge

            if (isNaN(totalCharge)) totalCharge = 0
            $('#'+creadit+'-premi-charge').html(ToRupiah.format(totalCharge).replaceAll('\u00A0', ''))
        })
        $(document).on('click', '#create-save', function () {
            loading()
            ajaxPost("{{ route('bgc') }}",fetchFormData(new FormData(document.getElementById('form-create'))),function(){
                clearForm('#form-create')
                $('#create-principal-address').html('-')
                $('#create-pic-name').html('-')
                $('#create-pic-position').html('-')
                $('#create-obligee-address').html('-')
                $('#create-premi-charge').html('Rp. 0')
                Swal.fire({
                    icon: "success",
                    title: "Request bank garansi berhasil dilakukan!",
                })
            })
        })
        $(document).on('change', '#create-obligee-id', function () {
            if($(this).val() != ''){
                const creadit = $(this).attr('id').split('-')[0] //create or edit
                ajaxGet('{{ route('client.obligee','-id-') }}'.replace('-id-',$(this).val()),null,function(response){
                    $('#'+creadit+'-obligee-address').html(response.data.address)
                })
            }
        })
        $(document).on('change', '#create-principal-id', function () {
            if($(this).val() != ''){
                const creadit = $(this).attr('id').split('-')[0] //create or edit
                ajaxGet('{{ route('client.principal','-id-') }}'.replace('-id-',$(this).val()),null,function(response){
                    const data = response.data
                    $('#'+creadit+'-principal-address').html(data.address)
                    $('#'+creadit+'-pic-name').html(data.pic_name)
                    $('#'+creadit+'-pic-position').html(data.pic_position)
                })
            }
        })
        $(document).on('input', '#create-start-date, #create-end-date, .create-due-day-tolerance', function () {
            const split = $(this).attr('id').split('-')
            let dayCount = (split[1]  == 'due') ? parseInt(calculateDayFromDates('start',split[0])) : calculateDayFromDates(split[1],split[0])
            $('#'+split[0]+'-day-count-input').val(dayCount)
            $('#'+split[0]+'-day-count').html(dayCount)
        })
    </script>
@endpush

resources/views/pdf.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
<body>
    {!! $content !!}
</body>
</html>