routes/web.php
<?php

use App\Http\Controllers\AgentController;
use App\Http\Controllers\AgentRateController;
use App\Http\Controllers\BankRateController;
use App\Http\Controllers\PrincipalController;
use App\Http\Controllers\BankAccountController;
use App\Http\Controllers\BankController;
use App\Http\Controllers\DesignController;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\InsuranceController;
use App\Http\Controllers\InsuranceTypeController;
use App\Http\Controllers\InsuranceRateController;
use App\Http\Controllers\ObligeeController;
use App\Http\Controllers\PDFDownloadController;
use App\Http\Controllers\RegionalController;
use App\Http\Controllers\Select2Controller;
use App\Http\Controllers\UploaderController;
use App\Http\Controllers\SuretyBondController;
use App\Http\Controllers\GuaranteeBankController;
use App\Http\Controllers\GuaranteeBankDraftController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\TemplateController;
use App\Http\Controllers\SuretyBondReportController;
use App\Http\Controllers\GuaranteeBankReportController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\InstalmentController;
use App\Http\Controllers\SuretyBondDraftController;
use App\Models\GuaranteeBankDraft;
use App\Models\SuretyBondDraft;
use Illuminate\Support\Facades\Route;
use App\Helpers\Jamsyar;
use App\Http\Controllers\GuaranteeBankReportPrintController;
use App\Http\Controllers\OtherReportController;
use App\Http\Controllers\OtherReportPrintController;
use App\Http\Controllers\SuretyBondReportPrintController;
use App\Http\Controllers\BankCostRateController;
use Illuminate\Support\Facades\Request;

/**
 * -------------------------------------------------------------------------
 * Design Only Route
 * -------------------------------------------------------------------------
 */

Route::get('/design/pdf/{page}', [DesignController::class, 'pdf'])->name('design.pdf');
Route::get('/design/{page}', [DesignController::class, 'page'])->name('design.page');

Route::get('/test', function (Request $request) {
    // dd(Jamsyar::cities('jsh','Semangat1','sura'));
    // dd(\App\Models\Branch::find(1)->table()->get());
    // dd(\App\Models\GuaranteeBank::table('remain',[])->get());
    // dd(\App\Models\Obligee::find(2)->sync());
    // dd(\App\Models\Principal::find(1)->sync());
    // dd(\App\Models\SuretyBond::find(5)->sync());
    // Jamsyar::token();
    // dd(Jamsyar::token());
});
Route::get('/subagent', function (Request $request) {
    $url = config('app.env') == 'local' ? 'http://devmicroservice.jamkrindosyariah.co.id/Api/get_subagen' : 'http://192.168.190.168:8002/Api/get_subagen';
    $response = \Illuminate\Support\Facades\Http::asJson()->acceptJson()->withToken(Jamsyar::login())
    ->post($url, [
        "kode_subagen" => "",
        "nama_subagen" => "",
        "limit" => 20,
        "offset" => 0
    ]);
    dd($response);
});


/**
 * -------------------------------------------------------------------------
 * Guest routes
 * -------------------------------------------------------------------------
 */
Route::get('request-surety-bond', [SuretyBondDraftController::class, 'indexClient'])->name('client');
Route::post('request-surety-bond', [SuretyBondDraftController::class, 'storeClient']);
Route::get('request-bank-garansi', [GuaranteeBankDraftController::class, 'indexClient'])->name('bgc');
Route::post('request-bank-garansi', [GuaranteeBankDraftController::class, 'storeClient']);
Route::get('principal-client/{principal}', [PrincipalController::class, 'show'])->name('client.principal');
Route::get('obligee-client/{obligee}', [ObligeeController::class, 'show'])->name('client.obligee');
Route::get('serviceworker.js', fn() => redirect()->route('main.dashboard')); // Entah kenapa beberapa kali login malah masuk ke sini

/**
 * -------------------------------------------------------------------------
 * Select2 Route
 * -------------------------------------------------------------------------
 */

Route::group(['prefix' => '/select2', 'as' => 'select2.'], function () {
    Route::get('regional',[Select2Controller::class,'regional'])->name('regional');
    Route::get('branch',[Select2Controller::class,'branch'])->name('branch');
    Route::get('branch-client',[Select2Controller::class,'branch_client'])->name('branchClient');
    Route::get('bank',[Select2Controller::class,'bank'])->name('bank');
    Route::get('province',[Select2Controller::class,'province'])->name('province');
    Route::get('city',[Select2Controller::class,'city'])->name('city');
    Route::get('agent',[Select2Controller::class,'agent'])->name('agent');
    Route::get('insurance',[Select2Controller::class,'insurance'])->name('insurance');
    Route::get('obligee',[Select2Controller::class,'obligee'])->name('obligee');
    Route::get('principal',[Select2Controller::class,'principal'])->name('principal');
    Route::get('insurance-type',[Select2Controller::class,'insuranceType'])->name('insuranceType');
    Route::get('suretyTemplate',[Select2Controller::class,'suretyTemplate'])->name('suretyTemplate');
    Route::get('bankTemplate/{id}',[Select2Controller::class,'bankTemplate'])->name('bankTemplate');
});

/*
|--------------------------------------------------------------------------
| Main Routes
|--------------------------------------------------------------------------
|
*/

Route::middleware(['auth'])->group(function () {
    Route::post('/uploader/tinymce', [UploaderController::class, 'tinyMCE'])->name('uploader.tinymce'); // tolong disesuaikan ya
    Route::get('/pdf/download/{id}', [PDFDownloadController::class, 'pdf']);
    Route::post('/pdf/download-template/', [PDFDownloadController::class, 'pdfTemplate'])->name('pdf.print');
    Route::post('/pdf/download-laporan-surety-bonds/', [PDFDownloadController::class, 'pdfSB'])->name('pdf.print.sb');

    // Master Data (bisa diakses di root dan beberapa di cabang)

    Route::group(['prefix' => '/master-data', 'as' => 'master.'], function () {
        Route::get('/', fn() => redirect(route('main.dashboard')));
        Route::apiResource('asuransi', InsuranceController::class)->names('insurances')->except('index');
        Route::apiResource('agen', AgentController::class)->names('agents')->except('index');
        Route::put('principal/{principal}/sync', [PrincipalController::class, 'sync'])->name('principals.sync');
        Route::post('principal/jamsyar-search', [PrincipalController::class, 'jamsyarSearch'])->name('principals.jamsyar-search');
        Route::post('principal/jamsyar-insert', [PrincipalController::class, 'jamsyarInsert'])->name('principals.jamsyar-insert');
        Route::apiResource('principal', PrincipalController::class)->names('principals')->except('index');
        Route::apiResource('rate-agen', AgentRateController::class)->names('agent-rates')->except('index');
        Route::apiResource('jenis-jaminan', InsuranceTypeController::class)->names('insurance-types')->except('index');
        Route::apiResource('rate-asuransi', InsuranceRateController::class)->names('insurance-rates')->except('index');
        Route::apiResource('rate-bank', BankRateController::class)->names('bank-rates')->except('index');
        Route::apiResource('bank', BankController::class)->names('banks')->except('index');
        Route::post('obligee/jamsyar-search', [ObligeeController::class, 'jamsyarSearch'])->name('obligees.jamsyar-search');
        Route::post('obligee/jamsyar-insert', [ObligeeController::class, 'jamsyarInsert'])->name('obligees.jamsyar-insert');
        Route::put('obligee/{obligee}/sync', [ObligeeController::class, 'sync'])->name('obligees.sync');
        Route::get('obligee/sync-with-jamsyar', [ObligeeController::class, 'jamsyar'])->name('obligees.jamsyar');
        Route::apiResource('obligee', ObligeeController::class)->names('obligees')->except('index');
        Route::apiResource('template', TemplateController::class)->names('templates')->except('index');
        Route::apiResource('bank-cost-rate', BankCostRateController::class)->names('bank-cost-rates')->except('index');
    });

    // Pembayaran (beberapa aksi bisa diakses di semua role)

    Route::group(['prefix' => '/pembayaran', 'as' => 'payments.'], function () {
        Route::get('/', [PaymentController::class, 'tables'])->name('tables');
        Route::post('hitung', [PaymentController::class, 'calculate'])->name('calculate');
        Route::apiResource('/payment', PaymentController::class, ['only' => ['store', 'show', 'destroy']])->names('payment');
    });

    // Admin Pusat

    Route::group(['middleware' => 'main', 'as' => 'main.'], function () {
        Route::get('/', DashboardController::class)->name('dashboard');
        Route::get('/profil', [ProfileController::class, 'index'])->name('profile');
        Route::apiResource('regional', RegionalController::class)->names('regionals');

        Route::group(['prefix' => '/master-data', 'as' => 'master.'], function () {
            Route::get('/', fn() => redirect(route('main.dashboard')));
            Route::get('asuransi', [InsuranceController::class, 'index'])->name('insurances.index');
            Route::get('agen', [AgentController::class, 'index'])->name('agents.index');
            Route::get('principal', [PrincipalController::class, 'index'])->name('principals.index');
            Route::get('rate-agen', [AgentRateController::class, 'index'])->name('agent-rates.index');
            Route::get('jenis-jaminan', [InsuranceTypeController::class, 'index'])->name('insurance-types.index');
            Route::get('rate-asuransi', [InsuranceRateController::class, 'index'])->name('insurance-rates.index');
            Route::get('rate-bank', [BankRateController::class, 'index'])->name('bank-rates.index');
            Route::get('bank', [BankController::class, 'index'])->name('banks.index');

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Sirius;
use App\Models\Branch;
use DB;
use Exception;
use App\Models\Payment;
use App\Models\Payable;
use Illuminate\Http\Request;

class PaymentController extends Controller
{
    public function indexPrincipalToBranch(Request $request){
        return view('payment.principal-to-branch');
    }
    public function indexRegionalToInsurance(Request $request){
        return view('payment.regional-to-insurance');
    }
    public function indexBranchToAgent(Request $request){
        return view('payment.branch-to-agent');
    }

    public function calculate(Request $request){
        try {
            $payment = Payment::fetch((object)$request->all());
            $totalBill = $payment->payment['total_bill'] ?? 0;
            $response = $this->response('OK',true,[
                'total_bill' => $totalBill,
                'total_bill_converted' => Sirius::toRupiah($totalBill, 2),
            ]);
            $http_code = 200;
        } catch (Exception $e) {
            $http_code = $this->httpErrorCode($e->getCode());
            $response = $this->errorResponse($e->getMessage());
        }
        return response()->json($response,$http_code);
    }
    public function calculateToRegional(Branch $regional, Branch $branch,Request $request){
        $request->merge(['branchId' => $branch->id,'regionalId' => $regional->id]);
        return $this->calculate($request);
    }
    public function tables(Request $request){
        $type = $request->type;
        $data = null;
        if($type == 'principal_to_branch'){
            $data = Payment::with('principal','branch')->select('payments.*')->where('branch_id', session()->get('branch')?->id)->whereType($type);
        }else if($type == 'regional_to_insurance'){
            $data = Payment::with('insurance','regional')->select('payments.*')->where('regional_id', session()->get('regional')?->id)->whereType($type);
        }else if($type == 'branch_to_agent'){
            $data = Payment::with('branch','agent')->select('payments.*')->where('branch_id', session()->get('branch')?->id)->whereType($type);
        }
        return datatables()->of($data)
        ->addIndexColumn()
        ->editColumn('paid_at', fn($payment) => strtoupper(Sirius::toLongDate($payment->paid_at)))
        ->editColumn('total_bill', fn($payment) => Sirius::toRupiah($payment->total_bill, 2))
        ->editColumn('action', 'datatables.actions-show-delete')
        ->toJson();
    }


    public function create()
    {
    }

    public function store(Request $request)
    {
        try {
            DB::beginTransaction();
            Payment::buat($request->all());
            $http_code = 200;
            $response = $this->storeResponse();
            DB::commit();
        } catch (Exception $e) {
            DB::rollback();
            $http_code = $this->httpErrorCode($e->getCode());
            $response = $this->errorResponse($e->getMessage());
        }

        return response()->json($response, $http_code);
    }
    public function storeToRegional(Branch $regional, Branch $branch, Request $request)
    {
        $request->merge(['branchId' => $branch->id,'regionalId' => $regional->id]);
        return $this->store($request);
    }

    public function show(Payment $payment)
    {
        $type = $payment->type;
        if($type == 'principal_to_branch'){
            $payment->principal;
            $payment->branch;
        }else if($type == 'branch_to_regional'){
            $payment->branch;
            $payment->regional;
        }else if($type == 'regional_to_insurance'){
            $payment->regional;
            $payment->insurance;
        }else if($type == 'branch_to_agent'){
            $payment->branch;
            $payment->agent;
        }

        return response()->json($this->showResponse($payment->toArray()));
    }

    public function edit(Payment $payment)
    {
    }

    public function update(Request $request, Payment $payment)
    {
    }

    public function destroy(Payment $payment)
    {
        try {
            DB::beginTransaction();
            $payment->hapus();
            $http_code = 200;
            $response = $this->destroyResponse();
            DB::commit();
        } catch (Exception $e) {
            DB::rollback();
            $http_code = $this->httpErrorCode($e->getCode());
            $response = $this->errorResponse($e->getMessage());
        }

        return response()->json($response, $http_code);
    }
}

resources/views/payment/branch-to-agent.blade.php
@extends('layouts.main', ['title' => 'Pembayaran Ke Agen'])

@push('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
@endpush

@section('contents')
    <x-card header="Daftar Pembayaran">
        @slot('headerAction')
            <x-button data-bs-toggle="modal" data-bs-target="#modal-create" size="sm" icon="bx bx-plus">Tambah Pembayaran</x-button>
        @endslot

        <x-table id="table">
            @slot('thead')
                <tr>
                    <th width="10px">No.</th>
                    <th>Waktu Bayar</th>
                    <th>Ke Agen</th>
                    <th>Nominal Bayar</th>
                    <th width="80px">Tindakan</th>
                </tr>
            @endslot
        </x-table>
    </x-card>
@endsection

@section('modals')
    @php
        $months = [];
        foreach (range(1, 12) as $month) {
            $months[$month] = strtoupper(Sirius::longMonth($month));
        }

        $years = [];
        foreach (range(date('Y'), 2000) as $year) {
            $years[$year] = $year;
        }
    @endphp

    <x-modal id="modal-create" title="Tambah Pembayaran" size="fullscreen">
        <x-form id="form-create" method="post">
            <input type="hidden" id="create-branch-id" class="calculate-params" name="branchId" value="{{ $global->branch->id }}">
            <x-form-input label="Waktu Bayar" id="create-paid-at" class-input="calculate-params" name="datetime" type="datetime-local" class="mb-3" required />
            <x-form-select label="Bulan" id="create-month" class-input="calculate-params" name="month" class="mb-3" :options="$months" value="{{ date('m') }}" required />
            <x-form-select label="Tahun" id="create-year" class-input="calculate-params" name="year" class="mb-3" :options="$years" value="{{ date('Y') }}" required />
            <x-form-select label="Ke Agen" id="create-agent-id" class-input="calculate-params" name="agentId" :options="[]" class="mb-3" required />
            <div class="mb-3">
                <x-form-label required>Total Tagihan</x-form-label>
                <div id="create-nominal">-</div>
            </div>
            <x-form-textarea label="Keterangan" id="create-desc" class-input="calculate-params" name="desc" />
        </x-form>

        @slot('footer')
            <x-button id="create-save" face="success" icon="bx bxs-save">Simpan</x-button>
        @endslot
    </x-modal>

    <x-modal id="modal-show" title="Detail Pembayaran">
        <div class="border-bottom pb-2 mb-2">
            <b>Waktu Bayar</b>: <br>
            <span id="show-paid-at">-</span>
        </div>
        <div class="border-bottom pb-2 mb-2">
            <b>Ke Agen</b>: <br>
            <span id="show-agent">-</span>
        </div>
        <div class="border-bottom pb-2 mb-2">
            <b>Nominal Bayar</b>: <br>
            <span id="show-nominal">Rp. 0</span>
        </div>
        <div>
            <b>Keterangan</b>: <br>
            <span id="show-desc">-</span>
        </div>
    </x-modal>
@endsection

@push('js')
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        let table = null
        let payment = null
        const type = 'branch_to_agent'
        $(document).ready(function () {
            table = dataTableInit('table','Pembayaran',{
                    url : '{{ route('payments.tables') }}',
                    data : { type : type }
                },[
                {data: 'paid_at'},
                {data: 'agent.name'},
                {data: 'total_bill'}
            ])
            $("#create-month, #create-year").select2({dropdownParent: $('#modal-create')})
            select2Init("#create-agent-id",'{{ route('select2.agent') }}',0,$('#modal-create'))
        })
        $(document).on('input', '.calculate-params', function () {
            const branchId = $('#create-branch-id').val()
            const agentId = $('#create-agent-id').val()
            const month = $('#create-month').val()
            const year = $('#create-year').val()
            if(branchId && agentId && month && year){
                $('#create-nominal').html(`<i class='fa-solid fa-spinner fa-spin me-2'></i>Menghitung ...`)
                let formData = new FormData(document.getElementById('form-create'))
                formData.append('type',type)
                ajaxPost("{{ route('payments.calculate') }}",formData,'',function(response){
                    if(response.success){
                        $('#create-nominal').html(response.data.total_bill_converted)
                    }
                },function (response) {
                    $('#create-nominal').html(`<span class='color-danger'><i class='fa-solid fa-x me-2'></i>`+response.message+`</span>`)
                },false)
            }
        })
        $(document).on('click', '#create-save', function () {
            loading()
            let formData = new FormData(document.getElementById('form-create'))
            formData.append('type',type)
            ajaxPost("{{ route('payments.payment.store') }}",formData,'#modal-create',function(){
                table.ajax.reload()
                clearForm('#form-create')
                $("#create-nominal").html('-')
                $('#create-year').val('{{ date('Y') }}').trigger('change')
                $('#create-month').val('{{ date('m') }}').trigger('change')
            })
        })
        $(document).on('click', '.btn-show', function () {
            ajaxGet("{{ route('payments.payment.show','-id-') }}".replace('-id-',$(this).data('id')),'',function(response){
                if(response.success){
                    payment = response.data
                    $('#show-paid-at').html(payment.paid_at_converted)
                    $('#show-agent').html(payment.agent.name)
                    $('#show-nominal').html(payment.total_bill_converted)
                    $('#show-desc').html(payment.desc ?? '-')
                }
            })
        })
        $(document).on('click', '.btn-delete', function () {
            // Delete
            NegativeConfirm.fire({
                title: "Yakin ingin menghapus pembayaran ini?",
            }).then((result) => {
                if (result.isConfirmed) {
                    loading()
                    ajaxPost("{{ route('payments.payment.destroy','-id-') }}".replace('-id-',$(this).data('id')),{_method:'delete'},'',function(){
                        table.ajax.reload()
                    })
                }
            })
        })
    </script>
@endpush

resources/views/payment/principal-to-branch.blade.php
@extends('layouts.main', ['title' => 'Pembayaran Dari Principal'])

@push('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
@endpush

@section('contents')
    <x-card header="Daftar Pembayaran">
        @slot('headerAction')
            <x-button data-bs-toggle="modal" data-bs-target="#modal-create" size="sm" icon="bx bx-plus">Tambah Pembayaran</x-button>
        @endslot

        <x-table id="table">
            @slot('thead')
                <tr>
                    <th width="10px">No.</th>
                    <th>Waktu Bayar</th>
                    <th>Dari Principal</th>
                    <th>Nominal Bayar</th>
                    <th width="80px">Tindakan</th>
                </tr>
            @endslot
        </x-table>
    </x-card>
@endsection

@section('modals')
    @php
        $months = [];
        foreach (range(1, 12) as $month) {
            $months[$month] = strtoupper(Sirius::longMonth($month));
        }

        $years = [];
        foreach (range(date('Y'), 2000) as $year) {
            $years[$year] = $year;
        }
    @endphp

    <x-modal id="modal-create" title="Tambah Pembayaran" size="fullscreen">
        <x-form id="form-create" method="post">
            <input type="hidden" id="create-branch-id" class="calculate-params" name="branchId" value="{{ $global->branch->id }}">
            <x-form-input label="Waktu Bayar" id="create-paid-at" name="paidAt" type="datetime-local" class="mb-3" required />
            <x-form-select label="Bulan" id="create-month" class-input="calculate-params" name="month" class="mb-3" :options="$months" value="{{ date('m') }}" required />
            <x-form-select label="Tahun" id="create-year" class-input="calculate-params" name="year" class="mb-3" :options="$years" value="{{ date('Y') }}" required />
            <x-form-select label="Dari Principal" id="create-principal-id" class-input="calculate-params" name="principalId" class="mb-3" required />
            <div class="mb-3">
                <x-form-label required>Nominal Bayar</x-form-label>
                <div id="create-nominal">-</div>
            </div>
            <x-form-textarea label="Keterangan" id="create-desc" name="desc" />
        </x-form>

        @slot('footer')
            <x-button id="create-save" face="success" icon="bx bxs-save">Simpan</x-button>
        @endslot
    </x-modal>

    <x-modal id="modal-show" title="Detail Pembayaran">
        <div class="border-bottom pb-2 mb-2">
            <b>Waktu Bayar</b>: <br>
            <span id="show-paid-at">-</span>
        </div>
        <div class="border-bottom pb-2 mb-2">
            <b>Dari Principal</b>: <br>
            <span id="show-principal">-</span>
        </div>
        <div class="border-bottom pb-2 mb-2">
            <b>Nominal Bayar</b>: <br>
            <span id="show-nominal">Rp. 0</span>
        </div>
        <div>
            <b>Keterangan</b>: <br>
            <span id="show-desc">-</span>
        </div>
    </x-modal>
@endsection

@push('js')
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        let table = null
        let payment = null
        const type = 'principal_to_branch'
        $(document).ready(function () {
            table = dataTableInit('table','Pembayaran',{
                    url : '{{ route('payments.tables') }}',
                    data : { type : type }
                },[
                {data: 'paid_at'},
                {data: 'principal.name'},
                {data: 'total_bill'}
            ])
            $("#create-month, #create-year").select2({dropdownParent: $('#modal-create')})
            select2Init("#create-principal-id",'{{ route('select2.principal') }}',0,$('#modal-create'))

            // $("#create-principal-id, #create-branch-id").select2({dropdownParent: $('#modal-create')})
            // $("#edit-principal-id, #edit-branch-id").select2({dropdownParent: $('#modal-edit')})
        })

        $(document).on('input', '.calculate-params', function () {
            const principalId = $('#create-principal-id').val()
            const branchId = $('#create-branch-id').val()
            const month = $('#create-month').val()
            const year = $('#create-year').val()
            if(principalId && branchId && month && year){
                $('#create-nominal').html(`<i class='fa-solid fa-spinner fa-spin me-2'></i>Menghitung ...`)
                let formData = new FormData(document.getElementById('form-create'))
                formData.append('type',type)
                ajaxPost("{{ route('payments.calculate') }}",formData,'',function(response){
                    if(response.success){
                        $('#create-nominal').html(response.data.total_converted)
                    }
                },function (response) {
                    $('#create-nominal').html(`<span class='color-danger'><i class='fa-solid fa-x me-2'></i>Terjadi masalah pada sistem</span>`)
                },false)
            }
        })
        $(document).on('click', '#create-save', function () {
            loading()
            let formData = new FormData(document.getElementById('form-create'))
            formData.append('type',type)
            ajaxPost("{{ route('payments.payment.store') }}",formData,'#modal-create',function(){
                table.ajax.reload()
                clearForm('#form-create')
                $("#create-nominal").html('-')
                $('#create-year').val('{{ date('Y') }}').trigger('change')
                $('#create-month').val('{{ date('m') }}').trigger('change')
            })
        })
        $(document).on('click', '.btn-show', function () {
            ajaxGet("{{ route('payments.payment.show','-id-') }}".replace('-id-',$(this).data('id')),'',function(response){
                if(response.success){
                    payment = response.data
                    $('#show-paid-at').html(payment.paid_at_converted)
                    $('#show-principal').html(payment.principal.name)
                    $('#show-nominal').html(payment.total_bill_converted)
                    $('#show-desc').html(payment.desc ?? '-')
                }
            })
        })
        $(document).on('click', '.btn-delete', function () {
            // Delete
            NegativeConfirm.fire({
                title: "Yakin ingin menghapus Pembayaran?",
            }).then((result) => {
                if (result.isConfirmed) {
                    loading()
                    ajaxPost("{{ route('payments.payment.destroy','-id-') }}".replace('-id-',$(this).data('id')),{_method:'delete'},'',function(){
                        table.ajax.reload()
                    })
                }
            })
        })
    </script>
@endpush